version: "3.9"
services:
  app:
    build: .
    container_name: postify
    env_file: .env
    environment:
      - MONGODB_URI=mongodb://mongo:27017/postify
      - DB_NAME=postify
      - LOG_LEVEL=info
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:7
    container_name: postify-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
